from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from . import __version__
from .app import doctor, initialize_project, project_status, remove_project, rollback, update_project
from .apply import ApplyOptions, apply_install_plan, load_apply_plan
from .migration import migrate_legacy_v1
from .packs import build_registry_install_plan, load_registry
from .packs.gsd_bridge import sync_gsd_config
from .paths import AppPaths
from .sources import verify_registry_sources
from .util import write_text_atomic
from .workflows import GSD_PINNED_VERSION, GsdInstallOptions, GsdWorkflowAdapter


COMMANDS = {
    "apply",
    "doctor",
    "gsd",
    "init",
    "migrate",
    "packs",
    "plan",
    "remove",
    "rollback",
    "sources",
    "status",
    "sync-gsd",
    "update",
    "workflow",
}
GLOBAL_FLAGS = {"--debug", "--ci"}


def _print_json(payload: object) -> None:
    text = json.dumps(payload, ensure_ascii=False, indent=2)
    stdout_buffer = getattr(sys.stdout, "buffer", None)
    if stdout_buffer is None:
        print(text)
        return
    stdout_buffer.write((text + "\n").encode("utf-8"))
    stdout_buffer.flush()


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ecc-init",
        description="Initialize, preview, update, diagnose, and remove ecc-init managed project configuration.",
    )
    parser.add_argument("--version", action="version", version=f"ecc-init {__version__}")
    parser.add_argument("--debug", action="store_true", help="show Python traceback for unexpected errors")
    parser.add_argument("--ci", action="store_true", help="prefer machine-friendly exit behavior for CI")
    sub = parser.add_subparsers(dest="command")

    init = sub.add_parser("init", help="initialize or preview the current project")
    init.add_argument("path", nargs="?", default=".")
    init.add_argument("--offline", action="store_true", help="use cached or bundled content only")
    init.add_argument("--no-sync", action="store_true", help="skip legacy ECC upstream sync")
    init.add_argument("--legacy", action="store_true", help="run the legacy 0.1.x initializer")
    init.add_argument("--profile", default="default", help="dry-run plan profile")
    init.add_argument("--pack", action="append", default=[], help="dry-run extra Pack")
    init.add_argument("--without-pack", action="append", default=[], help="dry-run excluded Pack")
    init.add_argument("--workflow", choices=["gsd", "none"], help="dry-run workflow override")
    init.add_argument("--install-gsd", action="store_true", help="install GSD Core before project apply; requires --yes")
    init.add_argument("--dry-run", action="store_true", help="preview registry-backed install plan without writing")
    init.add_argument("--yes", action="store_true", help="non-interactive confirmation for write operations")
    init.add_argument("--json", action="store_true", help="output JSON")

    plan = sub.add_parser("plan", help="preview a declarative install plan without writing files")
    plan.add_argument("path", nargs="?", default=".")
    plan.add_argument("--profile", default="default", help="declarative profile id")
    plan.add_argument("--pack", action="append", default=[], help="extra Pack; repeatable")
    plan.add_argument("--without-pack", action="append", default=[], help="excluded Pack; repeatable")
    plan.add_argument("--workflow", help="override the profile workflow")
    plan.add_argument("--json", action="store_true", help="output InstallPlan JSON")
    plan.add_argument("--output", help="write InstallPlan JSON to a file")

    apply = sub.add_parser("apply", help="preflight and apply an install plan; defaults to dry-run")
    apply.add_argument("plan", help="install-plan.json generated by ecc-init plan")
    apply.add_argument("--dry-run", action="store_true", help="validate only; never writes")
    apply.add_argument("--yes", action="store_true", help="allow write phases when available")
    apply.add_argument("--install-gsd", action="store_true", help="allow explicit device/runtime-level GSD install")
    apply.add_argument("--skip-gsd-check", action="store_true", help="skip GSD runtime status check; intended for CI/tests or when you intentionally manage GSD separately")
    apply.add_argument("--sync-gsd", dest="sync_gsd", action="store_true", help="preview GSD config sync")
    apply.add_argument("--no-sync-gsd", dest="sync_gsd", action="store_false", help="skip GSD config sync")
    apply.set_defaults(sync_gsd=None)
    apply.add_argument("--offline", action="store_true", help="do not use network-backed providers")
    apply.add_argument("--json", action="store_true", help="output JSON")

    gsd = sub.add_parser("gsd", help="manage device/runtime-level GSD Core")
    gsd_sub = gsd.add_subparsers(dest="gsd_command", required=True)
    for name in ("status", "install", "update", "verify"):
        gsd_cmd = gsd_sub.add_parser(name, help=f"{name} GSD Core for a runtime")
        gsd_cmd.add_argument("path", nargs="?", default=".")
        gsd_cmd.add_argument("--runtime", choices=["auto", "claude"], default="claude", help="GSD runtime; codex/cursor support depends on upstream GSD Core and is not yet a stable option")
        gsd_cmd.add_argument("--scope", choices=["global", "project"], default="global")
        gsd_cmd.add_argument("--version", default=GSD_PINNED_VERSION)
        gsd_cmd.add_argument("--dry-run", action="store_true", help="preview without executing installer")
        gsd_cmd.add_argument("--yes", action="store_true", help="execute install/update non-interactively")
        gsd_cmd.add_argument("--json", action="store_true", help="output JSON")

    packs = sub.add_parser("packs", help="inspect the declarative Pack registry")
    packs_sub = packs.add_subparsers(dest="packs_command", required=True)
    packs_list = packs_sub.add_parser("list", help="list Packs")
    packs_list.add_argument("--json", action="store_true", help="output JSON")
    packs_show = packs_sub.add_parser("show", help="show Pack details")
    packs_show.add_argument("pack")
    packs_show.add_argument("--json", action="store_true", help="output JSON")

    sources = sub.add_parser("sources", help="inspect and verify source declarations")
    sources_sub = sources.add_subparsers(dest="sources_command", required=True)
    sources_list = sources_sub.add_parser("list", help="list sources")
    sources_list.add_argument("--json", action="store_true", help="output JSON")
    sources_verify = sources_sub.add_parser("verify", help="verify source declarations")
    sources_verify.add_argument("--json", action="store_true", help="output JSON")

    workflow = sub.add_parser("workflow", help="inspect Workflow Adapter state")
    workflow_sub = workflow.add_subparsers(dest="workflow_command", required=True)
    workflow_status = workflow_sub.add_parser("status", help="show GSD adapter checks")
    workflow_status.add_argument("path", nargs="?", default=".")
    workflow_status.add_argument("--json", action="store_true", help="output JSON")

    sync_gsd = sub.add_parser("sync-gsd", help="merge Pack generated GSD config without overwriting user values")
    sync_gsd.add_argument("path", nargs="?", default=".")
    sync_gsd.add_argument("--profile", default="default", help="agent policy/profile")
    sync_gsd.add_argument("--pack", action="append", default=[], help="Pack to sync; repeatable")
    sync_gsd.add_argument("--dry-run", action="store_true", help="preview without writing config")
    sync_gsd.add_argument("--json", action="store_true", help="output JSON")

    migrate = sub.add_parser("migrate", help="preview or apply legacy v1 to v2 migration")
    migrate.add_argument("path", nargs="?", default=".")
    migrate.add_argument("--dry-run", action="store_true", help="preview migration actions without writing files")
    migrate.add_argument("--json", action="store_true", help="output migration report as JSON")

    status = sub.add_parser("status", help="show project detection and managed-file status")
    status.add_argument("path", nargs="?", default=".")
    status.add_argument("--json", action="store_true", help="output JSON")

    update = sub.add_parser("update", help="preview or apply source, workflow, and Pack updates")
    update.add_argument("path", nargs="?", default=".")
    update.add_argument("--profile", default="default", help="Pack profile to preview")
    update.add_argument("--pack", action="append", default=[], help="extra Pack to include")
    update.add_argument("--without-pack", action="append", default=[], help="Pack to exclude")
    update.add_argument("--source", action="append", default=[], help="source id to check; repeatable")
    update.add_argument("--sources", action="store_true", help="include source checks")
    update.add_argument("--workflow", action="store_true", help="include pinned workflow update command")
    update.add_argument("--packs", action="store_true", help="include Pack/GSD config update")
    update.add_argument("--check", action="store_true", help="check without writing")
    update.add_argument("--dry-run", action="store_true", help="preview without writing")
    update.add_argument("--yes", action="store_true", help="apply safe local update actions non-interactively")
    update.add_argument("--json", action="store_true", help="output JSON")
    update.add_argument("--ci", action="store_true", help="return CI-friendly exit codes")

    diagnose = sub.add_parser("doctor", help="check Python, Git, directories, resources, GSD, and tools")
    diagnose.add_argument("path", nargs="?", default=".")
    diagnose.add_argument("--mode", choices=["preflight", "audit"], default="preflight", help="preflight (before first apply) or audit (after apply)")
    diagnose.add_argument("--json", action="store_true", help="output JSON")
    diagnose.add_argument("--ci", action="store_true", help="return CI-friendly environment exit codes")

    restore = sub.add_parser("rollback", help="restore from a backup or operation receipt")
    restore.add_argument("path", nargs="?", default=".")
    restore.add_argument("--backup", dest="backup_id", help="backup id; defaults to latest backup")
    restore.add_argument("--operation-id", help="restore the backup recorded by an operation receipt")
    restore.add_argument("--receipt", help="restore the backup recorded by a receipt file")
    restore.add_argument("--json", action="store_true", help="output JSON")

    remove = sub.add_parser("remove", help="preview or remove ecc-init managed Pack/GSD bindings")
    remove.add_argument("path", nargs="?", default=".")
    remove.add_argument("--pack", action="append", default=[], help="Pack id to remove; repeatable")
    remove.add_argument("--workflow", action="store_true", help="include workflow removal strategy")
    remove.add_argument("--all", action="store_true", help="remove all registry-managed Pack bindings")
    remove.add_argument("--dry-run", action="store_true", help="preview without writing")
    remove.add_argument("--yes", action="store_true", help="apply safe local removals non-interactively")
    remove.add_argument("--json", action="store_true", help="output JSON")
    return parser


def _normalize_argv(argv: list[str]) -> list[str]:
    if not argv:
        return ["init"]
    if argv[0] in COMMANDS or argv[0] in {"--version", "-h", "--help"}:
        return argv
    if argv[0] in GLOBAL_FLAGS:
        head: list[str] = []
        rest = list(argv)
        while rest and rest[0] in GLOBAL_FLAGS:
            head.append(rest.pop(0))
        if not rest or rest[0] not in COMMANDS:
            return [*head, "init", *rest]
        return [*head, *rest]
    return ["init", *argv]


def _print_run_report(report) -> None:
    print(f"Project: {report.project_root}")
    print("Detected stacks: " + (", ".join(report.detection.stacks) if report.detection.stacks else "none"))
    if report.upstream_ref:
        print(f"ECC upstream ref: {report.upstream_ref}")
    counts: dict[str, int] = {}
    for result in report.results:
        counts[result.status] = counts.get(result.status, 0) + 1
        if result.status in {"conflict", "preserved"}:
            print(f"[needs attention] {result.path}: {result.message}")
    print("File results: " + ", ".join(f"{key}={value}" for key, value in sorted(counts.items())))
    if report.backup_id:
        print(f"Backup: {report.backup_id}")
    for warning in report.warnings:
        print(f"[warning] {warning}")
    if report.conflicts:
        print("Conflicts were preserved locally; inspect generated upstream/diff files.")


def _print_plan_summary(plan) -> None:
    print(f"Project: {plan.project_root}")
    print(f"Workflow: {plan.workflow} ({plan.workflow_scope})")
    print("Packs: " + (", ".join(plan.packs) if plan.packs else "none"))
    print(f"File operations: {len(plan.file_operations)}")
    print(f"External operations: {len(plan.external_operations)}")
    for warning in plan.warnings:
        print(f"[warning] {warning}")


def _print_pack_list(json_output: bool) -> None:
    registry = load_registry()
    items = [pack.to_dict() for pack in registry.packs.values()]
    if json_output:
        _print_json(items)
        return
    for pack in registry.packs.values():
        print(f"{pack.pack_id}\tv{pack.version}\t{pack.description}")


def _print_pack_show(pack_id: str, json_output: bool) -> int:
    registry = load_registry()
    pack = registry.packs.get(pack_id)
    if pack is None:
        print(f"unknown Pack: {pack_id}", file=sys.stderr)
        return 1
    payload = pack.to_dict()
    if json_output:
        _print_json(payload)
        return 0
    print(f"Pack: {pack.pack_id}")
    print(f"Version: {pack.version}")
    print(f"Description: {pack.description}")
    print("Components: " + (", ".join(pack.components) if pack.components else "none"))
    print("Requires: " + (", ".join(pack.requires) if pack.requires else "none"))
    print("Conflicts: " + (", ".join(pack.conflicts) if pack.conflicts else "none"))
    print("Stack conditions: " + (", ".join(pack.stack_conditions) if pack.stack_conditions else "none"))
    return 0


def _print_sources_list(json_output: bool) -> None:
    registry = load_registry()
    items = [source.to_dict() for source in registry.sources.values()]
    if json_output:
        _print_json(items)
        return
    for source in registry.sources.values():
        license_label = source.license_id or "unknown"
        print(f"{source.source_id}\t{source.kind}\t{license_label}\t{source.repository or source.package or ''}")


def _print_sources_verify(json_output: bool) -> int:
    registry = load_registry()
    checks = verify_registry_sources(registry)
    if json_output:
        _print_json([check.to_dict() for check in checks])
    else:
        for check in checks:
            print(f"[{'PASS' if check.ok else 'FAIL'}] {check.check_id}: {check.message} {check.detail}".rstrip())
    return 0 if all(check.ok for check in checks) else 1


def _workflow_result_payload(result) -> dict[str, object]:
    return {
        "workflow": result.workflow_id,
        "status": result.status,
        "checks": [check.__dict__ for check in result.checks],
        "commands": [
            {"args": list(command.args), "description": command.description, "dry_run": command.dry_run}
            for command in result.commands
        ],
        "warnings": list(result.warnings),
    }


def _print_workflow_status(path: Path, json_output: bool) -> int:
    result = GsdWorkflowAdapter().verify(AppPaths.build(path))
    if json_output:
        _print_json(_workflow_result_payload(result))
    else:
        print(f"Workflow: {result.workflow_id}")
        print(f"Status: {result.status}")
        for check in result.checks:
            print(f"[{'PASS' if check.ok else 'WARN'}] {check.check_id}: {check.message} {check.detail}".rstrip())
        print("[hint] Prefer `ecc-init gsd status` for device/runtime-level GSD checks.")
    return 0 if result.ok else 3


def _print_gsd(args) -> int:
    paths = AppPaths.build(Path(args.path))
    adapter = GsdWorkflowAdapter()
    effective_dry_run = args.dry_run or not args.yes
    options = GsdInstallOptions(
        runtime=args.runtime,
        scope=args.scope,
        version=args.version,
        yes=args.yes,
        dry_run=effective_dry_run,
    )
    if args.gsd_command == "status":
        result = adapter.status(paths, runtime=args.runtime, scope=args.scope)
    elif args.gsd_command == "verify":
        result = adapter.verify(paths, runtime=args.runtime, scope=args.scope)
    elif args.gsd_command == "install":
        result = adapter.install(paths, options)
    elif args.gsd_command == "update":
        result = adapter.update(paths, options)
    else:
        raise ValueError(f"unknown gsd command: {args.gsd_command}")

    if args.json:
        _print_json(_workflow_result_payload(result))
    else:
        print(f"GSD Core: {result.status}")
        print(f"Runtime: {args.runtime}")
        print(f"Scope: {args.scope}")
        if result.commands:
            print("Command: " + " ".join(result.commands[0].args))
            print("Mode: " + ("dry-run" if result.commands[0].dry_run else "apply"))
        for check in result.checks:
            print(f"[{'PASS' if check.ok else 'FAIL'}] {check.check_id}: {check.message} {check.detail}".rstrip())
        for warning in result.warnings:
            print(f"[warning] {warning}")
    if result.status == "not_installed":
        return 2
    if result.status == "blocked_environment":
        return 3
    return 0 if result.ok else 1


def _print_sync_gsd(args) -> int:
    report = sync_gsd_config(
        Path(args.path),
        profile_id=args.profile,
        packs=args.pack or None,
        dry_run=args.dry_run,
    )
    if args.json:
        _print_json(report.to_dict())
    else:
        print(f"GSD config: {report.config_path}")
        print(f"Initialized: {report.initialized}")
        print(f"Changed: {report.changed}")
        print("Mode: " + ("dry-run" if args.dry_run else "apply"))
        for warning in report.warnings:
            print(f"[warning] {warning}")
    return 0


def _print_migration_report(args) -> int:
    report = migrate_legacy_v1(Path(args.path), dry_run=args.dry_run)
    if args.json:
        _print_json(report.to_dict())
        return 0
    print(f"Migration project: {report.project_root}")
    print(f"Legacy v1 detected: {report.detected}")
    print("Mode: dry-run" if args.dry_run else "Mode: apply")
    print(f"Applied: {report.applied}")
    if report.backup_id:
        print(f"Backup: {report.backup_id}")
    if report.operation_id:
        print(f"Operation: {report.operation_id}")
    for action in report.actions:
        detail = f" ({action.reason})" if action.reason else ""
        print(f"[{action.status}] {action.action}: {action.path}{detail}")
    for warning in report.warnings:
        print(f"[warning] {warning}")
    return 0


def _doctor_payload(path: Path, mode: str = "preflight") -> dict[str, object]:
    checks = []
    summary = {"PASS": 0, "WARN": 0, "FAIL": 0}
    for check in doctor(path, mode=mode):
        status = "PASS" if check.ok else ("FAIL" if check.severity_if_failed == "fail" else "WARN")
        summary[status] += 1
        checks.append(
            {
                "check_id": check.check_id,
                "label": check.label,
                "status": status,
                "ok": check.ok,
                "severity_if_failed": check.severity_if_failed,
                "detail": check.detail,
            }
        )
    return {"project_root": str(Path(path).expanduser().resolve()), "mode": mode, "summary": summary, "checks": checks}


def _print_doctor(args) -> int:
    mode = getattr(args, "mode", "preflight")
    payload = _doctor_payload(Path(args.path), mode=mode)
    if args.json:
        _print_json(payload)
    else:
        print(f"Mode: {payload['mode']}")
        for check in payload["checks"]:
            print(f"[{check['status']}] {check['label']}: {check['detail']}")
    return 3 if payload["summary"]["FAIL"] else 0


def _print_status(args) -> int:
    status = project_status(Path(args.path))
    if args.json:
        _print_json(status)
        return 0
    print(f"Project: {status['project_root']}")
    print("Detected stacks: " + (", ".join(status["detected_stacks"]) or "none"))
    print("Global CLAUDE.md: " + ("present" if status["global_claude_md"] else "missing"))
    print("Global skills: " + (", ".join(status["global_skills"]) or "none"))
    print("Project skills: " + (", ".join(status["project_skills"]) or "none"))
    print("Code tour completed: " + ("yes" if status["code_tour_completed"] else "no"))
    print(f"Upstream ref: {status['upstream_ref'] or 'unknown'}")
    print(f"Last initialized: {status['last_initialized_at'] or 'never'}")
    print(f"Backup count: {status['backup_count']}")
    workflow = status["workflow"]
    planned_workflow = workflow.get("planned") or {}
    runtime = workflow.get("runtime") or {}
    print(
        "Workflow: "
        + (planned_workflow.get("id") or "unknown")
        + f" ({planned_workflow.get('scope') or 'unknown'}); GSD runtime: {runtime.get('status') or 'unknown'}"
    )
    packs = status["packs"]
    installed_packs = packs["installed"]
    if isinstance(installed_packs, dict):
        for pack_id, info in sorted(installed_packs.items()):
            status_label = info.get("status", "unknown") if isinstance(info, dict) else "installed"
            print(f"- {pack_id}: {status_label}")
    else:
        print("Installed Packs: " + (", ".join(sorted(installed_packs)) or "none"))
    print("Planned Packs: " + (", ".join(packs["planned"]) or "none"))
    source_lock = status["source_lock"]
    print(f"Source lock: {source_lock['status']} ({source_lock['source_count']} source(s))")
    receipt = status["last_receipt"]
    print(f"Last receipt: {receipt['status']} ({receipt.get('operation_id') or 'none'})")
    readiness = status["apply_readiness"]
    print(f"Apply readiness: {readiness['status']}")
    if status["conflicts"]:
        print("Conflict files:")
        for item in status["conflicts"]:
            print(f"- {item}")
    if status["modified_managed_files"]:
        print("Modified managed files:")
        for item in status["modified_managed_files"]:
            print(f"- {item}")
    return 0


def _print_update(args) -> int:
    report = update_project(
        Path(args.path),
        profile_id=args.profile,
        include_packs=args.pack,
        exclude_packs=args.without_pack,
        update_sources=args.sources,
        update_workflow=args.workflow,
        update_packs=args.packs,
        source_ids=args.source,
        check=args.check,
        dry_run=args.dry_run,
        yes=args.yes,
    )
    if args.json:
        _print_json(report.to_dict())
    else:
        print(f"Project: {report.project_root}")
        print("Mode: " + ("dry-run" if report.dry_run else "apply"))
        print(f"Sources checked: {len(report.source_checks)}")
        print(f"Workflow update: {report.workflow_result.status if report.workflow_result else 'not requested'}")
        print(f"Pack update changed: {report.config_report.changed if report.config_report else False}")
        if report.operation_id:
            print(f"Operation: {report.operation_id}")
        for warning in report.warnings:
            print(f"[warning] {warning}")
        for item in report.conflicts:
            print(f"[conflict] {item}")
        for item in report.modified_managed_files:
            print(f"[modified] {item}")
    if not report.source_ok:
        return 1
    if report.manual_action_required:
        return 2
    if report.workflow_result and not report.workflow_result.ok and not report.dry_run:
        return 1
    return 0


def _print_remove(args) -> int:
    report = remove_project(
        Path(args.path),
        pack_ids=args.pack,
        workflow=args.workflow,
        all_=args.all,
        dry_run=args.dry_run,
        yes=args.yes,
    )
    if args.json:
        _print_json(report.to_dict())
    else:
        print(f"Project: {report.project_root}")
        print("Mode: " + ("dry-run" if report.dry_run else "apply"))
        print("Packs: " + (", ".join(report.packs) if report.packs else "none"))
        print(f"Workflow removal: {report.remove_workflow}")
        print(f"GSD config: {report.config_path}")
        print(f"Changed: {report.changed}")
        if report.operation_id:
            print(f"Operation: {report.operation_id}")
        for warning in report.warnings:
            print(f"[warning] {warning}")
    return 0


def _print_apply(args) -> int:
    plan = load_apply_plan(Path(args.plan))
    effective_dry_run = args.dry_run or not args.yes
    report = apply_install_plan(
        plan,
        ApplyOptions(
            dry_run=effective_dry_run,
            yes=args.yes,
            skip_gsd_check=args.skip_gsd_check,
            sync_gsd=args.sync_gsd,
            offline=args.offline,
            install_gsd=args.install_gsd,
        ),
    )
    payload = report.to_dict()
    if args.json:
        _print_json(payload)
    else:
        print(f"Plan project: {report.project_root}")
        print(f"Workflow: {report.plan.workflow}")
        print(f"Packs: {', '.join(report.plan.packs) if report.plan.packs else 'none'}")
        print(f"Status: {report.status}")
        if report.operation_id:
            print(f"Operation: {report.operation_id}")
        if report.backup_id:
            print(f"Backup: {report.backup_id}")
        if report.sources_locked:
            print("Source lock: .claude/ecc-sources.lock.json")
        if report.operation_id:
            print()
            print("Rollback:")
            print(f"  ecc-init rollback . --operation-id {report.operation_id}")
        if report.device_side_effects:
            print()
            print("NOTE: Device/runtime-level side effects were produced.")
            print("These are NOT covered by project rollback:")
            for effect in report.device_side_effects:
                print(f"  - {effect['type']}: {effect['message']}")
        if report.config_report and report.config_report.get("initialized"):
            print(f"GSD config: {'synced' if report.config_report.get('changed') else 'unchanged'}")
        for warning in report.warnings:
            print(f"[warning] {warning}")
        for error in report.errors:
            print(f"[error] {error}")
    return 0 if report.status in {"dry_run", "applied", "applied_with_warnings"} and not report.errors else 4


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(_normalize_argv(list(sys.argv[1:] if argv is None else argv)))
    command = args.command or "init"
    try:
        if command == "init":
            if args.legacy:
                if args.dry_run:
                    print("ecc-init failed: --legacy cannot be combined with --dry-run; use migrate/update previews instead", file=sys.stderr)
                    return 1
                report = initialize_project(Path(args.path), offline=args.offline, no_sync=args.no_sync)
                if args.json:
                    _print_json(report.to_dict())
                else:
                    _print_run_report(report)
                return 2 if report.conflicts else 0
            if args.yes and not args.dry_run:
                paths = AppPaths.build(Path(args.path))
                gsd_result = None
                if args.install_gsd:
                    gsd_result = GsdWorkflowAdapter().install(
                        paths,
                        GsdInstallOptions(
                            runtime="claude",
                            scope="global",
                            version=GSD_PINNED_VERSION,
                            yes=True,
                            dry_run=False,
                        ),
                    )
                plan = build_registry_install_plan(
                    paths.project_root,
                    profile_id=args.profile,
                    include_packs=args.pack,
                    exclude_packs=args.without_pack,
                    workflow=args.workflow,
                )
                apply_report = apply_install_plan(
                    plan,
                    ApplyOptions(
                        dry_run=False,
                        yes=True,
                        expected_project_root=paths.project_root,
                        skip_gsd_check=bool(gsd_result and gsd_result.ok),
                    ),
                )
                if args.json:
                    _print_json(
                        {
                            "project_root": str(paths.project_root),
                            "gsd_install": _workflow_result_payload(gsd_result) if gsd_result else None,
                            "apply": apply_report.to_dict(),
                        }
                    )
                else:
                    print("GSD init separates device-level GSD Core install from project-level Pack apply.")
                    print(f"Project: {paths.project_root}")
                    print(f"GSD install: {gsd_result.status if gsd_result else 'not requested'}")
                    print(f"Apply status: {apply_report.status}")
                    if apply_report.operation_id:
                        print(f"Apply operation: {apply_report.operation_id}")
                    if apply_report.backup_id:
                        print(f"Backup: {apply_report.backup_id}")
                    written_count = len(apply_report.files_written)
                    skipped_count = len(apply_report.files_skipped)
                    print(f"Files written: {written_count}")
                    if skipped_count:
                        print(f"Files skipped: {skipped_count}")
                    if apply_report.sources_locked:
                        print("Source lock: .claude/ecc-sources.lock.json")
                    if apply_report.operation_id:
                        print(f"Receipt: ~/.ecc-init/operations/{apply_report.operation_id}/receipt.json")
                    if apply_report.packs_partial:
                        print()
                        print("Partial Packs:")
                        for pack_id in apply_report.packs_partial:
                            print(f"  - {pack_id}")
                    if apply_report.files_skipped:
                        print(f"Skipped components: {len(apply_report.files_skipped)}")
                    if apply_report.operation_id:
                        print()
                        print("Rollback:")
                        print(f"  ecc-init rollback . --operation-id {apply_report.operation_id}")
                    for warning in apply_report.warnings:
                        print(f"[warning] {warning}")
                    for error in apply_report.errors:
                        print(f"[error] {error}")
                if gsd_result and not gsd_result.ok:
                    return 3 if gsd_result.status == "blocked_environment" else 1
                success_statuses = {"applied", "applied_with_warnings"}
                return 0 if apply_report.status in success_statuses and not apply_report.errors else 4
            else:
                plan = build_registry_install_plan(
                    Path(args.path),
                    profile_id=args.profile,
                    include_packs=args.pack,
                    exclude_packs=args.without_pack,
                    workflow=args.workflow,
                )
                content = plan.to_json()
                if args.json:
                    print(content)
                else:
                    _print_plan_summary(plan)
                return 0
        if command == "plan":
            plan = build_registry_install_plan(
                Path(args.path),
                profile_id=args.profile,
                include_packs=args.pack,
                exclude_packs=args.without_pack,
                workflow=args.workflow,
            )
            content = plan.to_json()
            if args.output:
                write_text_atomic(Path(args.output), content + "\n")
            if args.json:
                print(content)
            else:
                _print_plan_summary(plan)
                if args.output:
                    print(f"Plan file: {Path(args.output)}")
            return 0
        if command == "apply":
            return _print_apply(args)
        if command == "gsd":
            return _print_gsd(args)
        if command == "packs":
            if args.packs_command == "list":
                _print_pack_list(args.json)
                return 0
            if args.packs_command == "show":
                return _print_pack_show(args.pack, args.json)
        if command == "sources":
            if args.sources_command == "list":
                _print_sources_list(args.json)
                return 0
            if args.sources_command == "verify":
                return _print_sources_verify(args.json)
        if command == "workflow":
            if args.workflow_command == "status":
                return _print_workflow_status(Path(args.path), args.json)
        if command == "sync-gsd":
            return _print_sync_gsd(args)
        if command == "migrate":
            return _print_migration_report(args)
        if command == "status":
            return _print_status(args)
        if command == "update":
            return _print_update(args)
        if command == "doctor":
            return _print_doctor(args)
        if command == "rollback":
            backup_id, count = rollback(
                Path(args.path),
                args.backup_id,
                args.operation_id,
                Path(args.receipt) if args.receipt else None,
            )
            if args.json:
                _print_json({"backup_id": backup_id, "restored": count})
            else:
                print(f"Restored {count} item(s) from backup {backup_id}.")
            return 0
        if command == "remove":
            return _print_remove(args)
    except Exception as exc:
        if getattr(args, "debug", False):
            raise
        print(f"ecc-init failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
